name: marmitia

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      DATABASE_URL: postgresql://marmitia:secret@db:5432/marmitia
    depends_on:
      db: 
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine

  worker:
    build: ./worker
    environment:
      REDIS_HOST: redis
      DATABASE_URL: postgresql://marmitia:secret@db:5432/marmitia
    depends_on:
      db: 
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: marmitia
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: marmitia
    volumes:
      - donnees-db:/var/lib/postgresql/data
    healthcheck:                                    # comment savoir si db est prête
      test: ["CMD-SHELL", "pg_isready -U marmitia"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  donnees-db: